# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tr2rl < Formula
  desc "Turn messy text lists, ASCII trees, and indented outlines into real project/directory structures instantly into desired path."
  homepage "https://github.com/cytificlabs/tr2rl"
  version "1.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.11/tr2rl_1.1.11_Darwin_x86_64.tar.gz"
      sha256 "0b7375373bdafa915b432c34864b8f54c3db99388befdef56458c441fc7c627b"

      def install
        bin.install "tr2rl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.11/tr2rl_1.1.11_Darwin_arm64.tar.gz"
      sha256 "65d1630069b06806f843163875b31a7d720179ac3444c34095c7e00dc517e4a1"

      def install
        bin.install "tr2rl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.11/tr2rl_1.1.11_Linux_x86_64.tar.gz"
      sha256 "caa25df0611c3ae1f27d60457c58f0076bf46c680ea1a817143672089ead24e4"
      def install
        bin.install "tr2rl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.11/tr2rl_1.1.11_Linux_arm64.tar.gz"
      sha256 "e230fbb4978dbc424121c76d75a5eeaf72d7252686877d0e4440793010d7f12c"
      def install
        bin.install "tr2rl"
      end
    end
  end
end
