# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tr2rl < Formula
  desc "Turn messy text lists, ASCII trees, and indented outlines into real project/directory structures instantly into desired path."
  homepage "https://github.com/cytificlabs/tr2rl"
  version "1.1.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.17/tr2rl_1.1.17_Darwin_x86_64.tar.gz"
      sha256 "379592d77bc725911ad8dfd6f7db7a3c1b40fe6891f57fb310bf4ad05b8f71ed"

      def install
        bin.install "tr2rl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.17/tr2rl_1.1.17_Darwin_arm64.tar.gz"
      sha256 "8a6c5df295f4ac32963c3b2186ae80ce36f0b9b45022b1a64a60b0cbb46bb325"

      def install
        bin.install "tr2rl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.17/tr2rl_1.1.17_Linux_x86_64.tar.gz"
      sha256 "d4d368cf9240f9f2b41d771165c037cc5a7acb6bda00acdf8f4eeeef5721d456"
      def install
        bin.install "tr2rl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cytificlabs/tr2rl/releases/download/v1.1.17/tr2rl_1.1.17_Linux_arm64.tar.gz"
      sha256 "77f1b6d3f13d1b4ba6c5b4a2da2b441b2d769cf88e9b35dfe64a50723715e9e9"
      def install
        bin.install "tr2rl"
      end
    end
  end
end
